pizzarestaurant/commande/urls.py
from django.urls import path
from . import  views

app_name = "commande"

urlpatterns = [
    path('', views.commande, name="index"),
]

pizzarestaurant/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

pizzarestaurant/menu/urls.py
from django.urls import path
from . import  views

app_name = "menu"

urlpatterns = [
    path('', views.index, name="index"),
]

pizzarestaurant/pizzarestaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
    path('commande/', include('commande.urls')),
]

pizzarestaurant/commande/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(null=True, blank=True)
    telephone = models.IntegerField()
    description_commande = models.TextField()
    

    class Meta:
        verbose_name = ("Commande")
        verbose_name_plural = ("Commandes")

    def __str__(self):
        return self.name

pizzarestaurant/main/models.py
from django.db import models


class pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredient = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

pizzarestaurant/menu/models.py
from django.db import models


class pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredient = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

pizzarestaurant/commande/views.py
from django.shortcuts import render
from .models import Contact
from .form import ContactForm


def commande(request):
   form = ContactForm()
   message = ''
   if request.method == "POST":
      form = ContactForm(request.POST)
      if form.is_valid():
         print(form.cleaned_data)
         new = Contact.objects.create(**form.cleaned_data)
         new.save()
         form = ContactForm
         message = 'Commande bien envoyée !'

   return render(request, 'commande/index.html', {'form': form, 'message':message})

pizzarestaurant/main/views.py
from django.shortcuts import render
# from django.http import HttpResponse

# Create your views here.


# /main
def index(request):
    return render(request, 'main/index.html')

pizzarestaurant/menu/views.py
from django.shortcuts import render
from .models import pizza


# Create your views here.

# / menu
def index(request):
    """pizzas = pizza.objects.all()
    pizzas_names_and_prices = [pizza.nom + ": " + str(pizza.prix) + " FCFA" for pizza in pizzas]
    pizzas_names_and_prices_str = ", ".join(pizzas_names_and_prices)
    return HttpResponse(f"Les pizzas: {pizzas_names_and_prices_str}")"""
   
    pizzas = pizza.objects.all().order_by("prix")
    return render(request, 'menu/index.html', {'pizzas': pizzas})

pizzarestaurant/commande/templates/commande/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Page de commande</title>
    <link rel="stylesheet" href="{% static 'commande/style.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <style>
                /* style pour desktop*/

        body{
            font-family: Cambria;
            font-size: larger;
        }

        .corps{
            background-color: rgba(29, 28, 27, 0.8);
            margin: 0px 350px 10px 350px;
            padding: 10px;
        }

        .titre{
            color: whitesmoke;
            font-size: 20px;
            text-align: center;
            text-shadow: 2px 2px 4px #000000;
        }

        .name{
            text-align: center;
            margin-top: 15px;
            height: 50px;
            width: 400px;
            font-family: Cambria;
            border: none;
            font-size: 18px;
            border-left: solid red 3px;
        }

        .email{
            text-align: center;
            margin-top: 15px;
            height: 50px;
            width: 400px;
            font-family: Cambria;
            border: none;
            font-size: 18px;
            border-left: solid rgb(3, 254, 3) 3px;
        }

        .telephone{
            text-align: center;
            margin-top: 15px;
            height: 50px;
            width: 400px;
            font-family: Cambria;
            border: none;
            font-size: 18px;
            border-left: solid red 3px;
        }

        .description{
            text-align: center;
            margin-top: 15px;
            padding-top: 10px;
            height: 100px;
            width: 400px;
            font-family: Cambria;
            border: none;
            font-size: 18px;
            border-left: solid red 3px;
        }

        .envoyer{
            margin-top: 15px;
            font-family: Cambria;
            font-size: 20px;
            padding: 6px 109px;
            color: black;
            background-color: rgb(247, 130, 5);
            border: solid whitesmoke 2px;
            cursor: pointer;
        }

        .envoyer:hover{
            background-color: blue;
            color: whitesmoke;
        }

        a{
            display: inline-block;
            text-decoration: none;
            font-size: 20px;
            padding: 5px 23.5px;
            border: solid 2px whitesmoke;
            margin: 38px 38px 10px 38px;
            background-color: rgb(247, 130, 5);
            color: black;
        }

        a:hover{
            background-color: blue;
            color: whitesmoke;
        }
           
        .retour{
            margin-top: 20px;
        }

        ::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
            color: rgb(69, 68, 68);
            opacity: 1; /* Firefox */
        }

        .reponse{
            text-align: center;
            color: rgb(6, 250, 6);
            font-style: italic;
        }

        .appel{
            text-align: center;
            color: whitesmoke;
            font-size: 20px;
        }

        /*responsive design for mobile*/
   
    </style>

</head>
<body>

    <div class="corps">
        <div>
            <p class="appel">
                Appelez-nous directement sur les numéros suivants: <br> <a style="text-decoration: none;" href="tel:+22897548961">97 54 89 61</a> ou <a style="text-decoration: none;" href="tel:+22890618954">90 61 89 54</a>
            <br> Ou alors...</p>
            <p class="titre">
                Veuillez remplir le formulaire de commande ci-dessous.
            </p>
        </div>
        <section class="form">
            {% block content %}
            <p class="reponse">{{ message }}</p>
            <center>
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="envoyer"> Envoyer la commande </button>
                </form>
            </center>
            {% endblock %}  
        </section>
        
        <center>
                <a style="text-decoration: none;" href="{% url 'menu:index' %}" class="retour"> Retour menu</a>
                <a style="text-decoration: none;" href="{% url 'main:index' %}" class="retour"> Retour accueil</a>
        </center>
    
    </div>

</body>
</html>

pizzarestaurant/main/templates/main/index.html
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>

    <style>
       /*  body{
    background: linear-gradient(0deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1)), url("https://png.pngtree.com/thumb_back/fh260/back_our/20190622/ourmid/pngtree-seafood-vegetable-pizza-gourmet-background-poster-image_214182.jpg") no-repeat center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    margin: 0;
    font-family: Arial;
    margin-bottom: 4%;
  } */

  .centrer{
    width: 500px;
    background-color: rgba(29, 28, 27, 0.7);
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    padding: 2% 4px;
  }

  .title{
    font-family: Arial;
    font-size: 30px;
    word-spacing: 30;
    letter-spacing: 2;
    padding-bottom: 20px;
    text-transform: uppercase;
    text-align: center;
    color: white;
    margin-top: -10px;
  }

  .texto{
    color: rgb(255, 247, 7);
    text-align: center;
    font-style: oblique;
    font-size: 20px;
    margin-top: -20px;
    text-transform: capitalize;
    font-family: 'Courier New', Courier, monospace;
  }

  a{
    display: block;
    text-align: center;
    color: black;
    margin-top: 30px;
    font-size: 22px;
    border: solid 2px whitesmoke;
    text-decoration: none;
    width: fit-content;
    padding: 5px 20px;
    margin-left: auto;
    margin-right: auto;
    background-color: rgb(247, 130, 5);
    font-family: Cambria;
  }

  a:hover{
    color: whitesmoke;
    background-color: blue;
    border: solid 2px whitesmoke;
  }

    </style>

</head>
<body>
   <div class="centrer">
    <h1 class="title">La Pizza De Maman</h1>
    <p class="texto">La Passion des pizza</p>
    <a href="{% url 'menu:index' %}">Consulter le menu</a>
    </div>
</body>
</html>

pizzarestaurant/menu/templates/menu/index.html
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>menu pizza mama</title>
    <style>
       /*  body{
          background: linear-gradient(0deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1)), url("https://media.istockphoto.com/id/1247815637/vector/pizza-slices-ingredients-black-textured-backround.jpg?s=612x612&w=0&k=20&c=6f2c3bl5xcksZJlWyBE5hx1yZ4wp8U03ZdlkeINVCMk=") no-repeat center fixed;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
          margin-bottom: 4%;
          font-family: Cambria;
      }
 */

      .mama{
        border: solid 1px whitesmoke;
        font-weight: bold;
        display: inline-block;
        padding: 20px 130px 0px 130px;
        text-decoration: none;
        text-transform: uppercase;
        color: whitesmoke;
        font-size: large;
        text-shadow: 2px 3px 2px #030303;
        background-color: rgba(29, 28, 27, 0.7);
      }

      .slogan{
        display: inline-block;
        margin-top: 0px;
        font-family: 'Courier New', Courier, monospace;
        color: rgb(245, 241, 1);
        text-transform:capitalize;
        text-shadow: 2px 2x 4px #fafafb;
        font-size: small;
        font-weight: normal;
      }
      h1{
        font-family: 'Courier New', Courier, monospace;
        display: inline-block;
        color: whitesmoke;
        font-size: large;
        background-color: rgb(250, 127, 3);
        padding: 15px 25px;
        font-weight: normal;
      }

      .menu_list{
        width: fit-content;
        background-color: rgba(29, 28, 27, 0.8);
        padding: 20px;
        margin-top: -35px;
      }

      .menu_list_item{
        margin: 35px 0px;
      }

      .menu_list_title{
        display: inline-block;
        text-align: left;
        color: whitesmoke;
        border-bottom: dotted 1px whitesmoke;
        text-transform: capitalize;
        font-weight: bold;
        font-size: 22px;
        font-family: Cambria;
        width: 350px;
      }

      .menu_list_prix{
        font-size: 12px;
        color: rgb(247, 251, 251);
        margin-left: 8px;
        font-style: italic;
        display: inline-block;
        width: 160px;
        height: 4%;
        font-weight: bold;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        text-align: center;
        background-color: rgb(250, 127, 3);
        border-radius: 50%;
        padding-top: 6px;
        padding-bottom: 4px;
      }

      .menu_list_ingredient{
        font-style: oblique;
        font-family: Cambria;
        font-size: 15px;
        color: white;
        opacity: 0.7;
        display: block;
        margin-top: 0px;
        width: 360px;
        text-transform: capitalize;
      }

      .badge{
        display: inline-block;
        background-color:black;
        color: whitesmoke;
        margin-top: -30px;
        padding: 5px 11px;
        border-radius: 15px;
        text-transform: lowercase;
      }

      .commande{
        background-color: rgb(247, 130, 5);
        display: inline-block;
        color: rgb(3, 4, 3);
        text-decoration: none;
        font-size: 20px;
        padding: 10px;
        border: solid 2px rgb(250, 248, 250);
        margin: -22px 0px -30px 0px;
      }

      .commande:hover{
        background-color: blue;
        display: inline-block;
        color: white;
        text-decoration: none;
        font-size: 20px;
        padding: 10px;
        border: solid 2px rgb(250, 248, 250);
        margin: -22px 0px -30px 0px;
      }

    </style>

</head>
<body>
    <center>
      <div>
        <a href="{% url 'main:index' %}" class="mama">P i z z a &nbsp;&nbsp  m a m a <br><p class="slogan">De bons ingredients, de bons pizzas !</p></a>
    </div>
    <div class="menu_title">
        <h1>Liste de nos pizzas</h1>
    </div>

    <div class="menu_list">
        {% for pizza in pizzas %}
            <div class="menu_list_item">
                <span class="menu_list_title">{{pizza.nom}}</span>
                <span class="menu_list_prix">{{pizza.prix | floatformat:2}} fcfa</span>
                <span class="menu_list_ingredient">{{pizza.ingredient}}</span>
            </div>
            {% if pizza.vegetarienne == True %}
                <span class="badge">végétarienne</span>
            {% endif %}
        {% endfor %}
    </div>
    
        <a href="{% url 'commande:index' %}" class="commande">Passer une commande</a> 
    </center>
</body>
</html>